#
# Module manifest for module 'Clockify'
#
# Generated by: Jeff Malavasi
#
# Generated on: 11/14/2020
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'PSClockify.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'


    # ID used to uniquely identify this module
    GUID              = 'a987de92-1f9a-4af8-9826-5bc86a658324'

    # Author of this module
    Author            = 'Jeff Malavasi'

    # Company or vendor of this module
    CompanyName       = 'malavasi.tech'

    # Copyright statement for this module
    Copyright         = '(c) 2020 Jeff Malavasi. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'A PowerShell module to interact with the Clockify API'

    # Compatible Versions of PS
    PowerShellVersion = '7.0'

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess  = 'PSClockify.Format.ps1xml'


    # Functions to export from this module
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport   = '*'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = 'Clockify'

}
